/* Auto-generated sample data so the demo loads without any network or file access. */
(function (SPF) { SPF.samples = {
 "scholars": [
  {
   "filename": "cv_ada_nwosu.txt",
   "text": "Ada Nwosu\nDepartment of Computer Science, Example State University\nada.nwosu@example.edu\n\nResearch Interests\nMachine learning, deep learning, natural language processing, and large-scale data\nanalysis. My group develops foundation models and text mining methods, with an\nemphasis on high-performance computing and scalable training on GPU clusters.\n\nEducation\nPh.D. in Computer Science, 2013\nB.S. in Computer Science, 2008\n\nAcademic Appointments\nAssociate Professor of Computer Science, 2019 to present\nAssistant Professor of Computer Science, 2014 to 2019\n\nSelected Publications\nNwosu, A. (2024). Scalable transformer models for scientific text mining. Journal of Machine Learning Research.\nNwosu, A. (2023). Deep learning for multilingual natural language processing. ACL.\nNwosu, A. (2022). Distributed training on GPU clusters for foundation models. SC22.\nNwosu, A. (2021). Text mining of environmental policy corpora. EMNLP.\nNwosu, A. (2019). Neural networks for time series forecasting. NeurIPS.\n\nGrants and Funding\nNational Science Foundation, \"Scalable Machine Learning for Scientific Discovery,\"\n$1,200,000, 2022 to 2025, Principal Investigator.\nNVIDIA industry gift for GPU cluster expansion, $150,000, 2021.\n\nTechnical Skills\nPython, PyTorch, distributed computing, high-performance computing, machine learning,\nnatural language processing, deep learning, data science.\n"
  },
  {
   "filename": "cv_ben_carter.txt",
   "text": "Ben Carter\nDepartment of Civil and Environmental Engineering, Example State University\nben.carter@example.edu\n\nResearch Interests\nWater resources engineering, hydrology, and watershed management. I study drought\nresilience and water security in arid regions, combining field data collection with\ngeospatial analysis and remote sensing. Recent work integrates low-cost sensor\nnetworks for real-time streamflow monitoring.\n\nEducation\nPh.D. in Civil Engineering, 2011\nM.S. in Environmental Engineering, 2007\n\nAcademic Appointments\nProfessor of Civil and Environmental Engineering, 2021 to present\nAssociate Professor, 2015 to 2021\n\nSelected Publications\nCarter, B. (2024). Sensor networks for streamflow monitoring in arid watersheds. Water Resources Research.\nCarter, B. (2023). Remote sensing of drought and water security. Journal of Hydrology.\nCarter, B. (2022). Geospatial analysis of watershed resilience. Environmental Modelling and Software.\nCarter, B. (2020). Field methods for hydrologic data collection. Hydrological Processes.\n\nGrants and Funding\nNational Science Foundation, \"Water Security in Arid Watersheds,\" $900,000,\n2021 to 2024, Principal Investigator.\nDepartment of Agriculture, \"Drought Resilience for Rural Water Systems,\" $600,000, 2019.\n\nTechnical Skills\nHydrologic modeling, GIS, remote sensing, geospatial analysis, sensor networks,\nfield data collection, water resources, environmental engineering.\n"
  },
  {
   "filename": "cv_clara_santos.txt",
   "text": "Clara Santos\nSchool of Public Health, Example State University\nclara.santos@example.edu\n\nResearch Interests\nEpidemiology and public health with a focus on health equity and health disparities\nin underserved communities. I use community-based participatory research, survey\nresearch, and mixed qualitative methods to study social determinants of health.\n\nEducation\nPh.D. in Epidemiology, 2012\nM.P.H. in Public Health, 2008\n\nAcademic Appointments\nAssociate Professor of Public Health, 2018 to present\nAssistant Professor, 2013 to 2018\n\nSelected Publications\nSantos, C. (2024). Community-based participatory research on health equity. American Journal of Public Health.\nSantos, C. (2023). Social determinants of health in rural communities. Health Affairs.\nSantos, C. (2022). Survey methods for underserved populations. Epidemiology.\nSantos, C. (2021). Environmental exposures and health disparities. Environmental Health Perspectives.\n\nGrants and Funding\nNational Institutes of Health, R01, \"Health Equity in Underserved Communities,\"\n$2,100,000, 2020 to 2025, Principal Investigator.\nRobert Wood Johnson Foundation, \"Community Health Partnerships,\" $400,000, 2018.\n\nTechnical Skills\nEpidemiology, biostatistics, survey research, community-based participatory research,\nqualitative methods, health equity, public health, community partnerships.\n"
  },
  {
   "filename": "cv_david_reyes.txt",
   "text": "David Reyes\nDepartment of Economics, Example State University\ndavid.reyes@example.edu\n\nResearch Interests\nApplied microeconomics with an emphasis on program evaluation, policy analysis, and\ncost-benefit analysis. I use econometrics and panel data methods, including\ninstrumental variables and randomized controlled trials, to evaluate the economic\nimpact of infrastructure and environmental policy.\n\nEducation\nPh.D. in Economics, 2010\nB.A. in Economics, 2004\n\nAcademic Appointments\nProfessor of Economics, 2020 to present\nAssociate Professor, 2015 to 2020\n\nSelected Publications\nReyes, D. (2024). Cost-benefit analysis of water infrastructure investment. Journal of Public Economics.\nReyes, D. (2023). Program evaluation of rural development policy. American Economic Review.\nReyes, D. (2022). Econometric impact evaluation of environmental regulation. Journal of Environmental Economics.\nReyes, D. (2021). Instrumental variables in field experiments. Econometrica.\n\nGrants and Funding\nNational Science Foundation, \"Economics of Infrastructure Resilience,\" $500,000,\n2021 to 2024, Principal Investigator.\nSloan Foundation, \"Policy Evaluation Methods,\" $250,000, 2019.\n\nTechnical Skills\nEconometrics, program evaluation, policy analysis, cost-benefit analysis, panel data,\ninstrumental variables, impact evaluation, statistical modeling, economics.\n"
  },
  {
   "filename": "cv_elena_petrova.txt",
   "text": "Elena Petrova\nDepartment of Electrical and Computer Engineering, Example State University\nelena.petrova@example.edu\n\nResearch Interests\nSensor systems, the Internet of Things, and embedded systems for environmental\nmonitoring. My lab designs low-power wireless sensor networks and edge devices, with\nexpertise in signal processing and real-time control systems.\n\nEducation\nPh.D. in Electrical Engineering, 2014\nM.S. in Electrical Engineering, 2010\n\nAcademic Appointments\nAssociate Professor of Electrical and Computer Engineering, 2020 to present\nAssistant Professor, 2015 to 2020\n\nSelected Publications\nPetrova, E. (2024). Low-power IoT sensor networks for environmental monitoring. IEEE Internet of Things Journal.\nPetrova, E. (2023). Edge computing for embedded sensor systems. IEEE Transactions on Industrial Electronics.\nPetrova, E. (2022). Signal processing for wireless sensor networks. IEEE Sensors Journal.\nPetrova, E. (2021). Real-time control of distributed sensors. IEEE Transactions on Control Systems.\n\nGrants and Funding\nNational Science Foundation, \"Wireless Sensor Networks for Environmental Sensing,\"\n$750,000, 2021 to 2024, Principal Investigator.\nDepartment of Defense, ONR, \"Edge Sensing Systems,\" $450,000, 2019.\n\nTechnical Skills\nSensor networks, Internet of Things, embedded systems, signal processing,\ncontrol systems, edge computing, wireless communication, electrical engineering.\n"
  },
  {
   "filename": "cv_farid_hassan.txt",
   "text": "Farid Hassan\nDepartment of Statistics and Data Science, Example State University\nfarid.hassan@example.edu\n\nResearch Interests\nStatistical modeling and data science for the environment, including geospatial\nanalysis, remote sensing, and climate data. I develop Bayesian methods and time\nseries models for large environmental datasets, and I work extensively with remote\nsensing imagery and spatial statistics.\n\nEducation\nPh.D. in Statistics, 2013\nM.S. in Applied Mathematics, 2009\n\nAcademic Appointments\nAssociate Professor of Statistics and Data Science, 2019 to present\nAssistant Professor, 2014 to 2019\n\nSelected Publications\nHassan, F. (2024). Bayesian spatial models for climate data. Journal of the American Statistical Association.\nHassan, F. (2023). Remote sensing and machine learning for land cover. Remote Sensing of Environment.\nHassan, F. (2022). Time series analysis of climate variability. Annals of Applied Statistics.\nHassan, F. (2021). Geospatial data science for environmental monitoring. Spatial Statistics.\n\nGrants and Funding\nNASA, \"Satellite Data Science for Climate,\" $650,000, 2021 to 2024, Principal Investigator.\nNational Science Foundation, \"Bayesian Methods for Environmental Data,\" $400,000, 2019.\n\nTechnical Skills\nStatistical modeling, Bayesian methods, geospatial analysis, remote sensing,\ntime series, data science, spatial statistics, climate, machine learning.\n"
  },
  {
   "filename": "cv_grace_kim.txt",
   "text": "Grace Kim\nDepartment of Communication Studies, Example State University\ngrace.kim@example.edu\n\nResearch Interests\nScience communication, media studies, and community engagement. I study how\ncommunities understand environmental risk, using qualitative methods, interviews,\nand focus groups. My work centers stakeholder engagement and community partnerships\nin participatory research.\n\nEducation\nPh.D. in Communication, 2012\nM.A. in Media Studies, 2008\n\nAcademic Appointments\nAssociate Professor of Communication Studies, 2018 to present\nAssistant Professor, 2013 to 2018\n\nSelected Publications\nKim, G. (2024). Communicating environmental risk in underserved communities. Journal of Communication.\nKim, G. (2023). Community engagement in participatory science. Public Understanding of Science.\nKim, G. (2022). Qualitative methods for stakeholder engagement. Qualitative Inquiry.\nKim, G. (2021). Media framing of climate and water issues. Environmental Communication.\n\nGrants and Funding\nNational Science Foundation, \"Broadening Participation in Environmental Science,\"\n$350,000, 2021 to 2024, Principal Investigator.\nNational Endowment for the Humanities, \"Public Science Narratives,\" $180,000, 2019.\n\nTechnical Skills\nScience communication, media studies, qualitative methods, interviews, focus groups,\ncommunity engagement, stakeholder engagement, community partnerships.\n"
  },
  {
   "filename": "cv_henry_okafor.txt",
   "text": "Henry Okafor\nDepartment of Computer Science, Example State University\nhenry.okafor@example.edu\n\nResearch Interests\nCybersecurity, privacy, and cryptography. My research addresses network security,\ntrustworthy computing, and privacy-preserving data analysis, including secure\nmachine learning and penetration testing of distributed systems.\n\nEducation\nPh.D. in Computer Science, 2015\nB.S. in Computer Engineering, 2010\n\nAcademic Appointments\nAssistant Professor of Computer Science, 2016 to present\n\nSelected Publications\nOkafor, H. (2024). Privacy-preserving machine learning for sensitive data. IEEE Security and Privacy.\nOkafor, H. (2023). Network security for distributed systems. USENIX Security.\nOkafor, H. (2022). Cryptographic protocols for trustworthy computing. ACM CCS.\nOkafor, H. (2021). Penetration testing of IoT devices. NDSS.\n\nGrants and Funding\nNational Science Foundation, \"Trustworthy Computing for Critical Infrastructure,\"\n$550,000, 2021 to 2024, Principal Investigator.\n\nTechnical Skills\nCybersecurity, cryptography, network security, privacy, penetration testing,\ntrustworthy computing, machine learning, computer science.\n"
  }
 ],
 "rfp": "National Science Foundation\nSmart and Connected Communities (S&CC)\nProgram Solicitation: AI-Enabled Water Sustainability and Climate Resilience for Underserved Communities\n\nSynopsis\nThe National Science Foundation invites proposals for integrative, use-inspired research\nthat improves water sustainability and climate resilience in underserved communities.\nSuccessful projects will pair advanced computing with environmental science and genuine\ncommunity engagement.\n\nAreas of Interest\nProposals should combine several of the following capabilities:\n\n- Artificial intelligence and machine learning for environmental data, including deep\n  learning and natural language processing of policy and community input.\n- Water resources, hydrology, drought, and water security, especially in arid regions.\n- Sensor networks, the Internet of Things, and embedded systems for real-time\n  environmental monitoring.\n- Geospatial analysis, remote sensing, and climate data for decision support.\n- Community-based participatory research, stakeholder engagement, and attention to\n  health equity in underserved populations.\n- Economic and policy analysis, including program evaluation and cost-benefit analysis\n  of proposed interventions.\n- Membrane desalination and water treatment technologies for reuse.\n- Integration of indigenous knowledge systems in environmental decision-making.\n\nBroader Impacts\nProjects must broaden participation and include a credible plan for community\npartnerships, workforce development, and translation of results into practice.\n\nAwards\nAnticipated total funding of $3,000,000 for approximately four awards. Interdisciplinary\nteams spanning computing, engineering, environmental science, health, and the social\nsciences are strongly encouraged.\n"
}; })(typeof window!=='undefined'?(window.SPF=window.SPF||{}):(globalThis.SPF=globalThis.SPF||{}));
